server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flyy
    username: root
    password: 2494088755
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    host: 127.0.0.1

  devtools:
    restart:
      enabled: true
      additional-paths: src/main #重启目录

  aop:
    auto: true
    proxy-target-class: true

  mail:
    host: smtp.163.com
    username: hy17623635027@163.com
    password: AZWLTDDSTDHDTIQC

mybatis-plus:
  #配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    map-underscore-to-camel-case: true
  #配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag #全局逻辑删除字段值
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
